# this should be a github action that runs every 1 hour, tries to run the project, and then creates a new pull request with the changes.

name: Fetch more

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  fetch-more:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
      - run: |
          pnpm install
      - name: Fetch
        run: |
          pnpm run do-it
      # - uses: peter-evans/create-pull-request@v5
      #   with:
      #     branch: more-data
      #     commit-message: "Add more data"
      #     title: "Fetch more data"
      #     delete-branch: true
      #     assignees: pvinis
      #     reviewers: pvinis
      - name: push to main
        # took this from https://github.com/mikeal/publish-to-github-action/blob/master/entrypoint.sh
        run: |
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config http.sslVerify false
          git config user.name "pavlobot"
          git config user.email "pavlobot@pvin.is"
          git remote add publisher "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose

          git checkout main
          git add -A
          git commit -m "add: more icons" || exit 0
          git pull --rebase publisher main
          git push publisher main
      # - uses: mikeal/publish-to-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH_NAME: main
