# this should be a github action that runs every 1 hour, tries to run the project, and then creates a new pull request with the changes.

name: Fetch more

on:
  schedule:
    - cron: "0,15,30,45 * * * *"
  workflow_dispatch:

jobs:
  fetch-more:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
      - run: |
          pnpm install
      - name: Fetch
        run: |
          pnpm run do-it
      # - uses: peter-evans/create-pull-request@v5
      #   with:
      #     branch: more-data
      #     commit-message: "Add more data"
      #     title: "Fetch more data"
      #     delete-branch: true
      #     assignees: pvinis
      #     reviewers: pvinis
      - uses: mikeal/publish-to-github-action@master
